name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  # Repositories are lowercase in GHCR
  IMAGE_NAME_FRONTEND: ghcr.io/aallaann1/calandar-frontend
  IMAGE_NAME_BACKEND: ghcr.io/aallaann1/calandar-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_NAME_FRONTEND }}:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_NAME_BACKEND }}:latest
